// Bandera: no requiere API key, se arma directo con el código ISO 3166-1 alpha-2.
export function bandeUrl(code) {
  if (!code) return null;
  return `https://flagcdn.com/48x36/${code.toLowerCase()}.png`;
}

// Lista completa embebida (no depende de una API externa, que puede caerse,
// pedir clave o cambiar de formato sin aviso).
export const PAISES = [
  { code: 'AF', nombre: 'Afganistán' },
  { code: 'AL', nombre: 'Albania' },
  { code: 'DE', nombre: 'Alemania' },
  { code: 'AD', nombre: 'Andorra' },
  { code: 'AO', nombre: 'Angola' },
  { code: 'AG', nombre: 'Antigua y Barbuda' },
  { code: 'SA', nombre: 'Arabia Saudita' },
  { code: 'DZ', nombre: 'Argelia' },
  { code: 'AR', nombre: 'Argentina' },
  { code: 'AM', nombre: 'Armenia' },
  { code: 'AU', nombre: 'Australia' },
  { code: 'AT', nombre: 'Austria' },
  { code: 'AZ', nombre: 'Azerbaiyán' },
  { code: 'BS', nombre: 'Bahamas' },
  { code: 'BH', nombre: 'Baréin' },
  { code: 'BD', nombre: 'Bangladés' },
  { code: 'BB', nombre: 'Barbados' },
  { code: 'BE', nombre: 'Bélgica' },
  { code: 'BZ', nombre: 'Belice' },
  { code: 'BJ', nombre: 'Benín' },
  { code: 'BY', nombre: 'Bielorrusia' },
  { code: 'MM', nombre: 'Birmania' },
  { code: 'BO', nombre: 'Bolivia' },
  { code: 'BA', nombre: 'Bosnia y Herzegovina' },
  { code: 'BW', nombre: 'Botsuana' },
  { code: 'BR', nombre: 'Brasil' },
  { code: 'BN', nombre: 'Brunéi' },
  { code: 'BG', nombre: 'Bulgaria' },
  { code: 'BF', nombre: 'Burkina Faso' },
  { code: 'BI', nombre: 'Burundi' },
  { code: 'BT', nombre: 'Bután' },
  { code: 'CV', nombre: 'Cabo Verde' },
  { code: 'KH', nombre: 'Camboya' },
  { code: 'CM', nombre: 'Camerún' },
  { code: 'CA', nombre: 'Canadá' },
  { code: 'QA', nombre: 'Catar' },
  { code: 'TD', nombre: 'Chad' },
  { code: 'CL', nombre: 'Chile' },
  { code: 'CN', nombre: 'China' },
  { code: 'CY', nombre: 'Chipre' },
  { code: 'VA', nombre: 'Ciudad del Vaticano' },
  { code: 'CO', nombre: 'Colombia' },
  { code: 'KM', nombre: 'Comoras' },
  { code: 'CG', nombre: 'Congo' },
  { code: 'CD', nombre: 'Congo (RD)' },
  { code: 'KP', nombre: 'Corea del Norte' },
  { code: 'KR', nombre: 'Corea del Sur' },
  { code: 'CI', nombre: 'Costa de Marfil' },
  { code: 'CR', nombre: 'Costa Rica' },
  { code: 'HR', nombre: 'Croacia' },
  { code: 'CU', nombre: 'Cuba' },
  { code: 'DK', nombre: 'Dinamarca' },
  { code: 'DM', nombre: 'Dominica' },
  { code: 'EC', nombre: 'Ecuador' },
  { code: 'EG', nombre: 'Egipto' },
  { code: 'SV', nombre: 'El Salvador' },
  { code: 'AE', nombre: 'Emiratos Árabes Unidos' },
  { code: 'ER', nombre: 'Eritrea' },
  { code: 'SK', nombre: 'Eslovaquia' },
  { code: 'SI', nombre: 'Eslovenia' },
  { code: 'ES', nombre: 'España' },
  { code: 'US', nombre: 'Estados Unidos' },
  { code: 'EE', nombre: 'Estonia' },
  { code: 'SZ', nombre: 'Esuatini' },
  { code: 'ET', nombre: 'Etiopía' },
  { code: 'PH', nombre: 'Filipinas' },
  { code: 'FI', nombre: 'Finlandia' },
  { code: 'FJ', nombre: 'Fiyi' },
  { code: 'FR', nombre: 'Francia' },
  { code: 'GA', nombre: 'Gabón' },
  { code: 'GM', nombre: 'Gambia' },
  { code: 'GE', nombre: 'Georgia' },
  { code: 'GH', nombre: 'Ghana' },
  { code: 'GD', nombre: 'Granada' },
  { code: 'GR', nombre: 'Grecia' },
  { code: 'GT', nombre: 'Guatemala' },
  { code: 'GY', nombre: 'Guyana' },
  { code: 'GN', nombre: 'Guinea' },
  { code: 'GQ', nombre: 'Guinea Ecuatorial' },
  { code: 'GW', nombre: 'Guinea-Bisáu' },
  { code: 'HT', nombre: 'Haití' },
  { code: 'HN', nombre: 'Honduras' },
  { code: 'HU', nombre: 'Hungría' },
  { code: 'IN', nombre: 'India' },
  { code: 'ID', nombre: 'Indonesia' },
  { code: 'IQ', nombre: 'Irak' },
  { code: 'IR', nombre: 'Irán' },
  { code: 'IE', nombre: 'Irlanda' },
  { code: 'IS', nombre: 'Islandia' },
  { code: 'SB', nombre: 'Islas Salomón' },
  { code: 'IL', nombre: 'Israel' },
  { code: 'IT', nombre: 'Italia' },
  { code: 'JM', nombre: 'Jamaica' },
  { code: 'JP', nombre: 'Japón' },
  { code: 'JO', nombre: 'Jordania' },
  { code: 'KZ', nombre: 'Kazajistán' },
  { code: 'KE', nombre: 'Kenia' },
  { code: 'KG', nombre: 'Kirguistán' },
  { code: 'KI', nombre: 'Kiribati' },
  { code: 'KW', nombre: 'Kuwait' },
  { code: 'LA', nombre: 'Laos' },
  { code: 'LS', nombre: 'Lesoto' },
  { code: 'LV', nombre: 'Letonia' },
  { code: 'LB', nombre: 'Líbano' },
  { code: 'LR', nombre: 'Liberia' },
  { code: 'LY', nombre: 'Libia' },
  { code: 'LI', nombre: 'Liechtenstein' },
  { code: 'LT', nombre: 'Lituania' },
  { code: 'LU', nombre: 'Luxemburgo' },
  { code: 'MK', nombre: 'Macedonia del Norte' },
  { code: 'MG', nombre: 'Madagascar' },
  { code: 'MY', nombre: 'Malasia' },
  { code: 'MW', nombre: 'Malaui' },
  { code: 'MV', nombre: 'Maldivas' },
  { code: 'ML', nombre: 'Malí' },
  { code: 'MT', nombre: 'Malta' },
  { code: 'MA', nombre: 'Marruecos' },
  { code: 'MU', nombre: 'Mauricio' },
  { code: 'MR', nombre: 'Mauritania' },
  { code: 'MX', nombre: 'México' },
  { code: 'FM', nombre: 'Micronesia' },
  { code: 'MD', nombre: 'Moldavia' },
  { code: 'MC', nombre: 'Mónaco' },
  { code: 'MN', nombre: 'Mongolia' },
  { code: 'ME', nombre: 'Montenegro' },
  { code: 'MZ', nombre: 'Mozambique' },
  { code: 'NA', nombre: 'Namibia' },
  { code: 'NR', nombre: 'Nauru' },
  { code: 'NP', nombre: 'Nepal' },
  { code: 'NI', nombre: 'Nicaragua' },
  { code: 'NE', nombre: 'Níger' },
  { code: 'NG', nombre: 'Nigeria' },
  { code: 'NO', nombre: 'Noruega' },
  { code: 'NZ', nombre: 'Nueva Zelanda' },
  { code: 'OM', nombre: 'Omán' },
  { code: 'NL', nombre: 'Países Bajos' },
  { code: 'PK', nombre: 'Pakistán' },
  { code: 'PW', nombre: 'Palaos' },
  { code: 'PA', nombre: 'Panamá' },
  { code: 'PG', nombre: 'Papúa Nueva Guinea' },
  { code: 'PY', nombre: 'Paraguay' },
  { code: 'PE', nombre: 'Perú' },
  { code: 'PL', nombre: 'Polonia' },
  { code: 'PT', nombre: 'Portugal' },
  { code: 'GB', nombre: 'Reino Unido' },
  { code: 'CF', nombre: 'República Centroafricana' },
  { code: 'CZ', nombre: 'República Checa' },
  { code: 'DO', nombre: 'República Dominicana' },
  { code: 'RW', nombre: 'Ruanda' },
  { code: 'RO', nombre: 'Rumania' },
  { code: 'RU', nombre: 'Rusia' },
  { code: 'WS', nombre: 'Samoa' },
  { code: 'KN', nombre: 'San Cristóbal y Nieves' },
  { code: 'SM', nombre: 'San Marino' },
  { code: 'VC', nombre: 'San Vicente y las Granadinas' },
  { code: 'LC', nombre: 'Santa Lucía' },
  { code: 'ST', nombre: 'Santo Tomé y Príncipe' },
  { code: 'SN', nombre: 'Senegal' },
  { code: 'RS', nombre: 'Serbia' },
  { code: 'SC', nombre: 'Seychelles' },
  { code: 'SL', nombre: 'Sierra Leona' },
  { code: 'SG', nombre: 'Singapur' },
  { code: 'SY', nombre: 'Siria' },
  { code: 'SO', nombre: 'Somalia' },
  { code: 'LK', nombre: 'Sri Lanka' },
  { code: 'ZA', nombre: 'Sudáfrica' },
  { code: 'SD', nombre: 'Sudán' },
  { code: 'SS', nombre: 'Sudán del Sur' },
  { code: 'SE', nombre: 'Suecia' },
  { code: 'CH', nombre: 'Suiza' },
  { code: 'SR', nombre: 'Surinam' },
  { code: 'TH', nombre: 'Tailandia' },
  { code: 'TZ', nombre: 'Tanzania' },
  { code: 'TJ', nombre: 'Tayikistán' },
  { code: 'TL', nombre: 'Timor Oriental' },
  { code: 'TG', nombre: 'Togo' },
  { code: 'TO', nombre: 'Tonga' },
  { code: 'TT', nombre: 'Trinidad y Tobago' },
  { code: 'TN', nombre: 'Túnez' },
  { code: 'TM', nombre: 'Turkmenistán' },
  { code: 'TR', nombre: 'Turquía' },
  { code: 'TV', nombre: 'Tuvalu' },
  { code: 'UA', nombre: 'Ucrania' },
  { code: 'UG', nombre: 'Uganda' },
  { code: 'UY', nombre: 'Uruguay' },
  { code: 'UZ', nombre: 'Uzbekistán' },
  { code: 'VU', nombre: 'Vanuatu' },
  { code: 'VE', nombre: 'Venezuela' },
  { code: 'VN', nombre: 'Vietnam' },
  { code: 'YE', nombre: 'Yemen' },
  { code: 'DJ', nombre: 'Yibuti' },
  { code: 'ZM', nombre: 'Zambia' },
  { code: 'ZW', nombre: 'Zimbabue' },
].sort((a, b) => a.nombre.localeCompare(b.nombre, 'es'));

export function nombrePais(code) {
  return PAISES.find((p) => p.code === code)?.nombre || code;
}